In [1]:
import pandas as pd

btc = pd.read_csv(r"binance_project_data\BTCUSDT\BTCUSDT_4h_merged.csv")
eth = pd.read_csv(r"binance_project_data\ETHUSDT\ETHUSDT_4h_merged.csv")

print("BTC shape:", btc.shape)
print("ETH shape:", eth.shape)

print("\nBTC columns:")
print(btc.columns.tolist())

print("\nETH columns:")
print(eth.columns.tolist())

print("\nBTC head:")
display(btc.head())

print("\nETH head:")
display(eth.head())

BTC shape: (4867, 22)
ETH shape: (4867, 22)

BTC columns:
['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore', 'fundingRate', 'markPrice', 'return_1', 'future_return_1', 'hl_spread', 'co_return', 'volume_change', 'ma_5', 'ma_20', 'volatility_20']

ETH columns:
['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time', 'quote_asset_volume', 'number_of_trades', 'taker_buy_base_asset_volume', 'taker_buy_quote_asset_volume', 'ignore', 'fundingRate', 'markPrice', 'return_1', 'future_return_1', 'hl_spread', 'co_return', 'volume_change', 'ma_5', 'ma_20', 'volatility_20']

BTC head:

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,...,fundingRate,markPrice,return_1,future_return_1,hl_spread,co_return,volume_change,ma_5,ma_20,volatility_20
0,2024-01-01 00:00:00+00:00,42283.58,42775.00,42230.08,42330.49,3948.08335,2024-01-01 03:59:59.999000+00:00,1.678186e+08,166013,2040.25881,...,NaN,NaN,NaN,0.003819,0.012873,0.001109,NaN,NaN,NaN,NaN
1,2024-01-01 04:00:00+00:00,42330.50,42500.00,42180.77,42492.46,2706.99880,2024-01-01 07:59:59.999000+00:00,1.146432e+08,128552,1385.79272,...,NaN,NaN,0.003819,0.004643,0.007513,0.003826,-0.314351,NaN,NaN,NaN
2,2024-01-01 08:00:00+00:00,42492.46,42762.39,42452.58,42690.20,2948.80274,2024-01-01 11:59:59.999000+00:00,1.257459e+08,137484,1523.25695,...,NaN,NaN,0.004643,0.002173,0.007257,0.004654,0.089325,NaN,NaN,NaN
3,2024-01-01 12:00:00+00:00,42690.21,42847.07,42580.00,42783.05,2936.44406,2024-01-01 15:59:59.999000+00:00,1.253587e+08,148756,1496.35093,...,NaN,NaN,0.002173,0.017032,0.006242,0.002175,-0.004191,NaN,NaN,NaN
4,2024-01-01 16:00:00+00:00,42783.05,43550.00,42664.42,43517.99,5686.97164,2024-01-01 19:59:59.999000+00:00,2.449706e+08,242235,3016.44908,...,NaN,NaN,0.017032,0.015088,0.020350,0.017178,0.936687,42762.838,NaN,NaN

ETH head:

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,...,fundingRate,markPrice,return_1,future_return_1,hl_spread,co_return,volume_change,ma_5,ma_20,volatility_20
0,2024-01-01 00:00:00+00:00,2281.87,2306.60,2271.00,2273.81,35739.3336,2024-01-01 03:59:59.999000+00:00,8.191288e+07,87164,17821.0674,...,NaN,NaN,NaN,0.004765,0.015657,-0.003532,NaN,NaN,NaN,NaN
1,2024-01-01 04:00:00+00:00,2273.80,2287.88,2265.24,2284.67,28107.5133,2024-01-01 07:59:59.999000+00:00,6.403174e+07,75452,14529.7001,...,NaN,NaN,0.004765,0.008629,0.009910,0.004781,-0.213541,NaN,NaN,NaN
2,2024-01-01 08:00:00+00:00,2284.68,2305.05,2280.00,2304.47,27894.1092,2024-01-01 11:59:59.999000+00:00,6.402866e+07,73647,14221.3256,...,NaN,NaN,0.008629,0.004429,0.010870,0.008662,-0.007592,NaN,NaN,NaN
3,2024-01-01 12:00:00+00:00,2304.47,2318.34,2294.84,2314.70,32165.8522,2024-01-01 15:59:59.999000+00:00,7.414646e+07,86973,16670.2894,...,NaN,NaN,0.004429,0.009699,0.010153,0.004439,0.153141,NaN,NaN,NaN
4,2024-01-01 16:00:00+00:00,2314.69,2340.98,2306.48,2337.26,46802.2526,2024-01-01 19:59:59.999000+00:00,1.086520e+08,111776,24815.5336,...,NaN,NaN,0.009699,0.006304,0.014761,0.009751,0.455029,2302.982,NaN,NaN